version: 0.0 
os: linux 
files: 
  - source: assetmgt
    destination: /opt/apache-tomcat-9.0.20/webapps/assetmgt/
hooks: 
  ApplicationStop: 
    - location: scripts/stop_application.sh 
      timeout: 300 
  BeforeInstall: 
    - location: scripts/uninstall_war_file.sh 
      timeout: 300 
  ApplicationStart: 
    - location: scripts/start_application.sh 
      tomcat: 300 