version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      # java: corretto11
    commands:
      - echo install phase
  pre_build:
    commands:
      - pwd
      - ls -lrta
      - npm install --location=global @angular/cli@latest
      # - npm install --location=global @angular/cli@13.3.8
      - npm install --legacy-peer-deps
      # - npm update --force
  build:
    commands:
      - echo Build Started
      - pwd
      - ls -lrta
      - npm run build_qa
      - ls -ltra dist
      - cd dist/assetmgt
      - ls -lrta
      - aws s3 sync . s3://wts-asset-mgmt-qa/
      - echo Files were uploaded unto s3 bucket
  post_build:
    commands:
      - echo "post build started `date`"
      - pwd
      - ls -lrta
      - aws cloudfront create-invalidation --distribution-id E2TC5IDC0F7SZL --paths "/*"
      - echo "Code has been deployed unto CloudFront `date`"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
